// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIYoul4aAvoLl9bfjNd_9ZD6dV72vZ6nc',
    appId: '1:987159892488:web:de6b6f68795de5b445f7bd',
    messagingSenderId: '987159892488',
    projectId: 'battleboatsv1',
    authDomain: 'battleboatsv1.firebaseapp.com',
    storageBucket: 'battleboatsv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOxcZkppNNfX4nAx4nhYEiGIfYkJxnds',
    appId: '1:987159892488:android:eacc277d9bb581ee45f7bd',
    messagingSenderId: '987159892488',
    projectId: 'battleboatsv1',
    storageBucket: 'battleboatsv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYW4WLqwLruH9uItyMHljJ1pH6Ukz08-I',
    appId: '1:987159892488:ios:07a8eb75de2727a045f7bd',
    messagingSenderId: '987159892488',
    projectId: 'battleboatsv1',
    storageBucket: 'battleboatsv1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYW4WLqwLruH9uItyMHljJ1pH6Ukz08-I',
    appId: '1:987159892488:ios:07a8eb75de2727a045f7bd',
    messagingSenderId: '987159892488',
    projectId: 'battleboatsv1',
    storageBucket: 'battleboatsv1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIYoul4aAvoLl9bfjNd_9ZD6dV72vZ6nc',
    appId: '1:987159892488:web:9986759dc386ec3745f7bd',
    messagingSenderId: '987159892488',
    projectId: 'battleboatsv1',
    authDomain: 'battleboatsv1.firebaseapp.com',
    storageBucket: 'battleboatsv1.firebasestorage.app',
  );
}
